version: '3.8'
services:
  web:
    container_name: odoo_container
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./mis_addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=wprgtmo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=5FTuX3a18
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./pg-web:/var/lib/pgadmin

volumes:
  odoo-web-data:
  odoo-db-data: